name: Push

on:
  push:
    branches: [ "develop", "master" ]
  workflow_dispatch:

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#         - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#         - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
#         - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
#     - uses: actions/
#     - run: echo "The ${{ github.repository }} repository has been cloned."
#     - run: echo "Setting up JDK" 
#     - name: set up JDK 11
#       uses: actions/setup-java@v3
#       with:
#         java-version: '11'
#         distribution: 'temurin'
#         cache: gradle
#     - run: echo "The workflow is now ready to test your code."
#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - run: echo "Building Debug APK."  
#     - name: Build with Gradle
#       run: ./gradlew build
#     - run: echo "Build status report=${{ job.status }}."


jobs:
  release:
   name: Release App Bundle
   needs: build
   runs-on: ubuntu-latest
   steps:
     - name: Download AAB from build
       uses: actions/download-artifact@v1
       with:
         name: aab
     - name: Create Release
       id: create_release
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: Tag Name
         release_name: Release Name
     - name: Upload Release AAB
       id: upload_release_asset
       uses: actions/upload-release-asset@v1.0.1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: aab/app-release.aab
         asset_name: ${{ github.event.repository.name }}.aab
         asset_content_type: application/zip
     - run: echo "Upload returned with status=${{ job.status }}."
